### ISSUE TITLE
v2.1.0 "dunno about this gcc"; gcc 5.2.1

### ISSUE THREAD

**Issue by koefoed** [stnava/ANTs#228]
Hello,

This may be an issue with the version of ITK that you are using and not ANTs.

I have downloaded version [v2.1.0](https://github.com/stnava/ANTs/archive/v2.1.0.tar.gz), unpacked it, made a build dir, done cmake ../ANTs-2.1.0, and make

I get this error:
```
In file included from /tmp/blap/build-fail/ITKv4/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_iosfwd.h:8:0,
                 from /tmp/blap/build-fail/ITKv4/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_iostream.h:27,
                 from /tmp/blap/build-fail/ITKv4/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_deprecated.cxx:4:
/tmp/blap/build-fail/ITKv4/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_compiler.h:130:4: error: #error "Dunno about this gcc"
 #  error "Dunno about this gcc"
    ^
Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/build.make:62: recipe for target 'Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/vcl_deprecated.cxx.o' failed
```

I am using:
```
$ gcc --version
gcc (Debian 5.2.1-17) 5.2.1 20150911
```

gcc version 5 is not covered by the long if-elif in the referenced file.
This may be related to a bug [reported in the ITK bug-system](https://issues.itk.org/jira/browse/ITK-3361)

Regards

**Comment by stnava** [comment]
you might try to use the current source version hosted on github.


brian

**Comment by gdevenyi** [comment]
<driveby comment> Since we're talking compilers, I thought I'd comment that ANTS builds and seems to work fine on the Intel 15.0.2 compiler in linux </driveby comment>
